image: registry.gitlab.com/yakshaving.art/go-builder:0.0.1

stages:
  - build
  - image

before_script:
  - mkdir -p /go/src/gitlab.com/$CI_PROJECT_NAMESPACE
  - cd /go/src/gitlab.com/$CI_PROJECT_NAMESPACE
  - ln -s $CI_PROJECT_DIR 
  - cd /go/src/gitlab.com/$CI_PROJECT_PATH
  - dep ensure

build:
  stage: build
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  artifacts:
    paths:
    - hurrdurr
  script:
  - make test
  - make build

image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:latest
