project_name: hurrdurr
release:
  github:
    owner: yakshaving-art
    name: hurrdurr
  name_template: '{{ .Tag }}'
builds:
- goos:
  - linux
  goarch:
    - amd64
  main: .
  binary: hurrdurr
  ldflags: -s -w -X gitlab.com/yakshaving.art/hurrdurr/version.Version={{.Version}} -X gitlab.com/yakshaving.art/hurrdurr/version.Commit={{.Commit}} -X gitlab.com/yakshaving.art/hurrdurr/version.Date={{.Date}}

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
changelog:
  filters:
    exclude:
      - typo
      - Fix
      - Merge
      - WIP
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
dockers:
- image: gitlab.com/yakshaving/hurrdurr
  goos: linux
  goarch: amd64
  goarm: ''
  binary: hurrdurr
  dockerfile: Dockerfile.amd64
env_files:
  github_token: ~/.goreleaser.token
