project_name: hurrdurr

release:
  # Disable github release
  disable: true

builds:
- goos:
  - linux
  goarch:
    - amd64
  main: .
  binary: hurrdurr
  ldflags: -s -w -X gitlab.com/yakshaving.art/hurrdurr/version.Version={{.Version}} -X gitlab.com/yakshaving.art/hurrdurr/version.Commit={{.Commit}} -X gitlab.com/yakshaving.art/hurrdurr/version.Date={{.Date}}

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
changelog:
  filters:
    exclude:
      - typo
      - Fix
      - Merge
      - WIP

archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*

dockers:
  - dockerfile: Dockerfile.amd64
    image_templates:
    - 'gitlab.com/yakshaving/hurrdurr:{{ .Tag }}'
